services:
  - type: web
    name: rps # the name of this service, eg your app name
    env: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
